name_label_thread_direction = "Направление резьбы"
name_right_thread = "Правая резьба"
name_left_thread = "Левая резьба"

name_warning_common_title = "Ошибка"
name_profile_type_error = "Ошибка в типе профиля!"
name_warning_common_error = "Ошибка при построении!\n\nПроверте корректность введённых параметров и повторите попытку."
name_warning_default_circle_info = "Ошибка при построении!\n\nЧто-то пошло не так. Повторите попытку."
name_warning_object_edge_error = "Ошибка при построении!\n\nБыло выбрано ребро эскиза.\nНеобходимо выделить ребро объекта."
name_warning_edge_type_error = "Ошибка при построении!\n\nНе было выбрано ребро формы 'Окружность'.\nНеобходимо выделить ребро объекта."
name_warning_edge_select_error = "Ошибка при построении!\n\nНе было выбрано ребро.\nНеобходимо выделить ребро объекта."