name_frame_thread_setting = "Параметры резьбы"
name_frame_thread_type = "Параметры профиля"
name_label_end_condition = "Граничные условия"
name_label_thread_pitch = "Шаг резьбы"
name_label_thread_direction = "Направление резьбы"
name_right_thread = "Правая резьба"
name_left_thread = "Левая резьба"
name_label_thread_type = "Тип резьбы"

name_error_kompas_api_title = "Ошибка"
name_error_kompas_api_connect = "Ошибка!\n\nНет активного документа.\nНеобходимо открыть документ типа 'Деталь'."
name_warning_common_title = "Ошибка"
name_profile_type_error = "Ошибка в типе профиля!"
name_warning_common_error = "Ошибка при построении!\n\nПроверте корректность введённых параметров и повторите попытку."
name_warning_default_circle_info = "Ошибка при построении!\n\nЧто-то пошло не так. Повторите попытку."
name_warning_object_edge_error = "Ошибка при построении!\n\nБыло выбрано ребро эскиза.\nНеобходимо выделить ребро объекта."
name_warning_edge_type_error = "Ошибка при построении!\n\nНе было выбрано ребро формы 'Окружность'.\nНеобходимо выделить ребро объекта."
name_warning_edge_select_error = "Ошибка при построении!\n\nНе было выбрано ребро.\nНеобходимо выделить ребро объекта."
